// print Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//find the sum of the even-valued terms.

fib = 1
bucketA = 1
bucketB = 0
total = 0

while fib < 4000000:
  bucketB = fib
  fib = fib + bucketA
  print (fib)
  bucketA = bucketB
  #if fib >4000000:
  # print (total)
#else:
  #bucketA = bucketB
  #if fib%2 == 0:
    #total = total+fib



  
print (total)

